package com.talkdesk.challenge.mapper;

import com.talkdesk.challenge.entity.Employee;
import com.talkdesk.challenge.model.EmployeeDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;


/**
 * This is a MapStruct mapper, used to convert between objects. The implementation code is generated by an annotation
 * processor.
 * <p>
 * Please refer to the MapStruct documentation: https://mapstruct.org/documentation.
 * <p>
 * MapStruct was choosen because it seems to be one of the mapping libraries with best performance:
 * https://www.baeldung.com/java-performance-mapping-frameworks
 */
@Mapper
public interface EmployeeMapper {
    EmployeeMapper INSTANCE = Mappers.getMapper(EmployeeMapper.class);

    Employee employeeDTOToEmployee(EmployeeDTO source);

    EmployeeDTO employeeToEmployeeDTO(Employee source);

    List<EmployeeDTO> employeeListToEmployeeDTOList(List<Employee> sourceList);


}
